//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOST.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryPlayerAnswer
    {
        public int idanswer { get; set; }
        public int idplayer { get; set; }
        public int idcategory { get; set; }
        public string answer { get; set; }
        public int round { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual GameCategory GameCategory { get; set; }
    }
}
