//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOST.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DostDatabase : DbContext
    {
        public DostDatabase()
            : base("name=DostDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GameCategory> GameCategory { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<CategoryPlayerAnswer> CategoryPlayerAnswer { get; set; }
    }
}
