//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOST.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestaCategoriaJugador
    {
        public int idrespuesta { get; set; }
        public int idjugador { get; set; }
        public int idcategoria { get; set; }
        public string respuesta { get; set; }
        public int ronda { get; set; }
    
        public virtual CategoriaPartida CategoriaPartida { get; set; }
        public virtual Jugador Jugador { get; set; }
    }
}
