//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOST.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DOST.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una cuenta registrada con ese nombre de usuario o correo..
        /// </summary>
        public static string AccountExistsRegisterErrorText {
            get {
                return ResourceManager.GetString("AccountExistsRegisterErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes confirmar tu cuenta para iniciar sesión. Verifica tu correo electrónico..
        /// </summary>
        public static string AccountNotConfirmedErrorText {
            get {
                return ResourceManager.GetString("AccountNotConfirmedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta registrada. Por favor, revisa tu correo para activar tu cuenta..
        /// </summary>
        public static string AccountRegisteredText {
            get {
                return ResourceManager.GetString("AccountRegisteredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el nombre de la nueva categoría.
        /// </summary>
        public static string AddCategoryNameText {
            get {
                return ResourceManager.GetString("AddCategoryNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar nueva categoría - DOST.
        /// </summary>
        public static string AddCategoryWindowTitle {
            get {
                return ResourceManager.GetString("AddCategoryWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error..
        /// </summary>
        public static string AnErrorHasOcurredErrorText {
            get {
                return ResourceManager.GetString("AnErrorHasOcurredErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animal.
        /// </summary>
        public static string AnimalCategoryText {
            get {
                return ResourceManager.GetString("AnimalCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejores puntuaciones.
        /// </summary>
        public static string BestScoresButton {
            get {
                return ResourceManager.GetString("BestScoresButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejores puntuaciones.
        /// </summary>
        public static string BestScoresText {
            get {
                return ResourceManager.GetString("BestScoresText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejores puntuaciones - DOST.
        /// </summary>
        public static string BestScoresWindowTItle {
            get {
                return ResourceManager.GetString("BestScoresWindowTItle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorías.
        /// </summary>
        public static string CategoriesText {
            get {
                return ResourceManager.GetString("CategoriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambios guardados..
        /// </summary>
        public static string ChangesSavedText {
            get {
                return ResourceManager.GetString("ChangesSavedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido al chat de la partida..
        /// </summary>
        public static string ChatWelcomeText {
            get {
                return ResourceManager.GetString("ChatWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monedas: .
        /// </summary>
        public static string CoinsText {
            get {
                return ResourceManager.GetString("CoinsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        public static string ColorCategoryText {
            get {
                return ResourceManager.GetString("ColorCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string ConfigurationButton {
            get {
                return ResourceManager.GetString("ConfigurationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar partida - DOST.
        /// </summary>
        public static string ConfigureGameWindowTitle {
            get {
                return ResourceManager.GetString("ConfigureGameWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar correo.
        /// </summary>
        public static string ConfirmEmailText {
            get {
                return ResourceManager.GetString("ConfirmEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string ConfirmPasswordText {
            get {
                return ResourceManager.GetString("ConfirmPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo: 20 monedas.
        /// </summary>
        public static string Cost20CoinsSelectionText {
            get {
                return ResourceManager.GetString("Cost20CoinsSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo: Gratis.
        /// </summary>
        public static string CostFreeLetterSelectionText {
            get {
                return ResourceManager.GetString("CostFreeLetterSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear la partida..
        /// </summary>
        public static string CouldntCreateGameErrorText {
            get {
                return ResourceManager.GetString("CouldntCreateGameErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al unirse a la partida..
        /// </summary>
        public static string CouldntJoinToGameErrorText {
            get {
                return ResourceManager.GetString("CouldntJoinToGameErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al seleccionar la letra..
        /// </summary>
        public static string CouldntSelectLetterErrorText {
            get {
                return ResourceManager.GetString("CouldntSelectLetterErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creado por.
        /// </summary>
        public static string CreatedByText {
            get {
                return ResourceManager.GetString("CreatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string CreateGameButton {
            get {
                return ResourceManager.GetString("CreateGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faltan campos por completar..
        /// </summary>
        public static string EmptyFieldsErrorText {
            get {
                return ResourceManager.GetString("EmptyFieldsErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin de la ronda.
        /// </summary>
        public static string EndOfTheRoundText {
            get {
                return ResourceManager.GetString("EndOfTheRoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string ExitButton {
            get {
                return ResourceManager.GetString("ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fruta.
        /// </summary>
        public static string FruitCategoryText {
            get {
                return ResourceManager.GetString("FruitCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración de la partida.
        /// </summary>
        public static string GameConfigurationText {
            get {
                return ResourceManager.GetString("GameConfigurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida de .
        /// </summary>
        public static string GameNameText {
            get {
                return ResourceManager.GetString("GameNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados de la partida - DOST.
        /// </summary>
        public static string GameResultsWindowTitle {
            get {
                return ResourceManager.GetString("GameResultsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida.
        /// </summary>
        public static string GameText {
            get {
                return ResourceManager.GetString("GameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtener palabra.
        /// </summary>
        public static string GetWordButton {
            get {
                return ResourceManager.GetString("GetWordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anfitrión.
        /// </summary>
        public static string HostPlayerText {
            get {
                return ResourceManager.GetString("HostPlayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes ingresar datos válidos..
        /// </summary>
        public static string InvalidDataErrorText {
            get {
                return ResourceManager.GetString("InvalidDataErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a partida.
        /// </summary>
        public static string JoinGameButton {
            get {
                return ResourceManager.GetString("JoinGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma cambiado. Reinicie el juego para aplicar los cambios..
        /// </summary>
        public static string LanguageChangedText {
            get {
                return ResourceManager.GetString("LanguageChangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string LastNameCategoryText {
            get {
                return ResourceManager.GetString("LastNameCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección de letra.
        /// </summary>
        public static string LetterSelectionWindowTitle {
            get {
                return ResourceManager.GetString("LetterSelectionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby - DOST.
        /// </summary>
        public static string LobbyWindowTitle {
            get {
                return ResourceManager.GetString("LobbyWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe una cuenta registrada con estos datos..
        /// </summary>
        public static string LoginErrorText {
            get {
                return ResourceManager.GetString("LoginErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión - DOST.
        /// </summary>
        public static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú principal - DOST.
        /// </summary>
        public static string MainMenuWindowTitle {
            get {
                return ResourceManager.GetString("MainMenuWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe haber un mínimo de 2 jugadores para iniciar la partida..
        /// </summary>
        public static string MustHaveAtLeastTwoPlayersErrorText {
            get {
                return ResourceManager.GetString("MustHaveAtLeastTwoPlayersErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes seleccionar una letra..
        /// </summary>
        public static string MustSelectALetterErrorText {
            get {
                return ResourceManager.GetString("MustSelectALetterErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes tener al menos 1 categoría seleccionada en la lista..
        /// </summary>
        public static string MustSelectAtLeastOneCategoryErrorText {
            get {
                return ResourceManager.GetString("MustSelectAtLeastOneCategoryErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string NameCategoryText {
            get {
                return ResourceManager.GetString("NameCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes ingresar un nombre válido..
        /// </summary>
        public static string NewCategoryNameEmptyErrorText {
            get {
                return ResourceManager.GetString("NewCategoryNameEmptyErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al iniciar la ronda. No se encontró un anfitrión..
        /// </summary>
        public static string NoHostFoundErrorText {
            get {
                return ResourceManager.GetString("NoHostFoundErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No clasificado.
        /// </summary>
        public static string NotRankedText {
            get {
                return ResourceManager.GetString("NotRankedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No listo.
        /// </summary>
        public static string NotReadyText {
            get {
                return ResourceManager.GetString("NotReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº de jugadores.
        /// </summary>
        public static string NumberOfPlayersText {
            get {
                return ResourceManager.GetString("NumberOfPlayersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No todos los jugadores están listos..
        /// </summary>
        public static string PlayersNotReadyErrorText {
            get {
                return ResourceManager.GetString("PlayersNotReadyErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador.
        /// </summary>
        public static string PlayerText {
            get {
                return ResourceManager.GetString("PlayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clasificación.
        /// </summary>
        public static string RankGameText {
            get {
                return ResourceManager.GetString("RankGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición: .
        /// </summary>
        public static string RankText {
            get {
                return ResourceManager.GetString("RankText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listo.
        /// </summary>
        public static string ReadyButton {
            get {
                return ResourceManager.GetString("ReadyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listo.
        /// </summary>
        public static string ReadyText {
            get {
                return ResourceManager.GetString("ReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar cuenta - DOST.
        /// </summary>
        public static string RegisterWindowTitle {
            get {
                return ResourceManager.GetString("RegisterWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados.
        /// </summary>
        public static string ResultsText {
            get {
                return ResourceManager.GetString("ResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string ReturnButton {
            get {
                return ResourceManager.GetString("ReturnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados de la ronda - DOST.
        /// </summary>
        public static string RoundResultsWindowTitle {
            get {
                return ResourceManager.GetString("RoundResultsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ronda .
        /// </summary>
        public static string RoundText {
            get {
                return ResourceManager.GetString("RoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos.
        /// </summary>
        public static string ScorePointsText {
            get {
                return ResourceManager.GetString("ScorePointsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntuación.
        /// </summary>
        public static string ScoreText {
            get {
                return ResourceManager.GetString("ScoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar letra a decisión.
        /// </summary>
        public static string SelectASpecificLetterButton {
            get {
                return ResourceManager.GetString("SelectASpecificLetterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string SelectButton {
            get {
                return ResourceManager.GetString("SelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar letra.
        /// </summary>
        public static string SelectLetterText {
            get {
                return ResourceManager.GetString("SelectLetterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar letra al azar.
        /// </summary>
        public static string SelectRandomLetterButton {
            get {
                return ResourceManager.GetString("SelectRandomLetterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar partida.
        /// </summary>
        public static string StartGameButton {
            get {
                return ResourceManager.GetString("StartGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al iniciar la partida..
        /// </summary>
        public static string StartGameErrorText {
            get {
                return ResourceManager.GetString("StartGameErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string StatusText {
            get {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo restante: .
        /// </summary>
        public static string TimeRemainingText {
            get {
                return ResourceManager.GetString("TimeRemainingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faltan campos por completar..
        /// </summary>
        public static string UncompletedFieldsErrorText {
            get {
                return ResourceManager.GetString("UncompletedFieldsErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo o la contraseña no coincide con su campo de confirmación..
        /// </summary>
        public static string UnmatchedRegisterFieldsErrorText {
            get {
                return ResourceManager.GetString("UnmatchedRegisterFieldsErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string UsernameText {
            get {
                return ResourceManager.GetString("UsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando a que se seleccione una letra....
        /// </summary>
        public static string WaitingForLetterSelectionText {
            get {
                return ResourceManager.GetString("WaitingForLetterSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando a más jugadores.
        /// </summary>
        public static string WaitingForPlayersText {
            get {
                return ResourceManager.GetString("WaitingForPlayersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando jugador.
        /// </summary>
        public static string WaitingForPlayerText {
            get {
                return ResourceManager.GetString("WaitingForPlayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró una palabra para esta categoría..
        /// </summary>
        public static string WordNotFoundErrorText {
            get {
                return ResourceManager.GetString("WordNotFoundErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya estás dentro de una partida..
        /// </summary>
        public static string YouAreAlreadyInAGame {
            get {
                return ResourceManager.GetString("YouAreAlreadyInAGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes suficientes monedas para hacer esto..
        /// </summary>
        public static string YouDontHaveEnoughCoinsErrorText {
            get {
                return ResourceManager.GetString("YouDontHaveEnoughCoinsErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes suficientes puntos para hacer esto..
        /// </summary>
        public static string YouDontHaveEnoughScorePointsErrorText {
            get {
                return ResourceManager.GetString("YouDontHaveEnoughScorePointsErrorText", resourceCulture);
            }
        }
    }
}
